Metrics/AbcSize:
  Max: 20

Metrics/MethodLength:
  Max: 15

Style/BlockDelimiters:
  Enabled: false

Style/DotPosition:
  EnforcedStyle: trailing

Style/IfUnlessModifier:
  Enabled: false

Style/MultilineOperationIndentation:
  EnforcedStyle: indented
