source 'https://rubygems.org'

gem 'rake', '~> 10.0'

# Helpers
gem 'i18n', '~> 0.6'
gem 'linguistics', '~> 2.0'

# Debugging
gem 'byebug', '~> 3.4'

# Testing
gem 'guard', '~> 1.2'
gem 'guard-bundler', '~> 1.0'
gem 'guard-minitest', '~> 0.5'
