source 'https://rubygems.org'

gem 'rake', '~> 10.4'

# Helpers
gem 'i18n', '~> 0.7'
gem 'linguistics', '~> 2.0'

# Debugging
gem 'byebug', '~> 3.5'

# Testing
gem 'guard', '~> 2.11'
gem 'guard-bundler', '~> 2.1'
gem 'guard-minitest', '~> 2.4'
